#ifndef PROTOCOLQCMODE_H
#define PROTOCOLQCMODE_H
#include "Network/Protocols/SerialProtocol.h"

enum CMD_PROTOCOL_QC_MODE
{
    CMD_PROTOCOL_QC_MODE_DISPENSE_TEST = 0x01,
    CMD_PROTOCOL_QC_MODE_ASP_TEST,
    CMD_PROTOCOL_QC_MODE_TUBE_FULL_REAGENT, //deprecated
    CMD_PROTOCOL_QC_MODE_TUBE_REMAIN_REAGENT, //deprecated
    CMD_PROTOCOL_QC_MODE_SHAKE_ANGLE_MIN, //deprecated
    CMD_PROTOCOL_QC_MODE_SHAKE_ANGLE_MAX, //deprecated
    CMD_PROTOCOL_QC_MODE_FUNCTION_PRIME,
    CMD_PROTOCOL_QC_MODE_FUNCTION_ROLL_BACK,
    CMD_PROTOCOL_QC_MODE_FUNCTION_SHAKE,
    CMD_PROTOCOL_QC_MODE_FUNCTION_DRY,
    CMD_PROTOCOL_QC_MODE_PUMP_OFFSET,
    CMD_PROTOCOL_QC_MODE_BATH_DSP,
    CMD_PROTOCOL_QC_MODE_BATH_ASP,
    CMD_PROTOCOL_QC_MODE_FAN_TEST,
    CMD_PROTOCOL_QC_MODE_STATUS_LED,
    /*S-Blot2 Easy Plus Addtional*/
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_TEMP_CH1_WRITE = 0x13,
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_TEMP_CH1_READ,
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_TEMP_CH2_WRITE,
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_TEMP_CH2_READ,
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_ON_OFF,
    CMD_PROTOCOL_QC_MODE_HEATING_PAD_TEMPERATURE_READ,
    CMD_PROTOCOL_QC_MODE_ADC_RAW_DATA_REVERSE_TEMPERATURE
};

#endif // PROTOCOLQCMODE_H
