#ifndef PROTOCOL_PUMP_SETTING_MODE_H
#define PROTOCOL_PUMP_SETTING_MODE_H
#include "Network/Protocols/SerialProtocol.h"

enum CMD_PROTOCOL_PUMP_SETTING_MODE
{
    CMD_PROTOCOL_PUMP_SETTING_MODE_RUN_STOP = 0x01, //deprecated
    CMD_PROTOCOL_PUMP_SETTING_MODE_TIME_PER_FLUX, //deprecated
    CMD_PROTOCOL_PUMP_SETTING_MODE_MOTION_SET, //deprecated
    CMD_PROTOCOL_PUMP_SETTING_MODE_PUMP_RUN_AUTO_CALIBRATION_SET,
    CMD_PROTOCOL_PUMP_SETTING_MODE_PUMP_RUN_AUTO_CALIBRATION_EXCU,
    CMD_PROTOCOL_PUMP_SETTING_MODE_USE_TIME_SET,
    CMD_PROTOCOL_PUMP_SETTING_MODE_USE_TIME_READ,
    CMD_PROTOCOL_PUMP_SETTING_MODE_OFFSET_SET,
    CMD_PROTOCOL_PUMP_SETTING_MODE_CAL_DISPENSE_NUMBER,  //deprecated
    CMD_PROTOCOL_PUMP_SETTING_MODE_PRIME_MAX_TIME = 0x0B, // TDOD : 변수명 변경해야함
    CMD_PROTOCOL_PUMP_SETTING_MODE_ROLL_BACK = 0x0D,
    CMD_PROTOCOL_PUMP_SETTING_MODE_AUTO_CALIBRATION_SET,
    CMD_PROTOCOL_PUMP_SETTING_MODE_AUTO_CALIBRATION_RUN,
    CMD_PROTOCOL_PUMP_SETTING_MODE_AMOUNT_BATH_READ = 0x10,
    CMD_PROTOCOL_PUMP_SETTING_MODE_OFFSET_READ = 0x18
};



#endif // PROTOCOL_PUMP_SETTING_MODE_H
