#ifndef PROTOCOLMOTORSETTINGMODE_H
#define PROTOCOLMOTORSETTINGMODE_H
#include "Network/Protocols/SerialProtocol.h"

enum CMD_MOTOR_SETTING_MODE
{
    CMD_MOTOR_SETTING_MODE_ASP_HOME = 0x01,
    CMD_MOTOR_SETTING_MODE_ASP_JOG_RUN,
    CMD_MOTOR_SETTING_MODE_BATH_ASP_PIN_HEIGHT_SET,
    CMD_MOTOR_SETTING_MODE_BATH_ASP_PIN_HEIGHT_READ,
    CMD_MOTOR_SETTING_MODE_TRAY_ASP_PIN_HEIGHT_SET,
    CMD_MOTOR_SETTING_MODE_TRAY_ASP_PIN_HEIGHT_READ,    //06
    CMD_MOTOR_SETTING_MODE_SHAKE_MIN_POS_SET = 0x08,
    CMD_MOTOR_SETTING_MODE_SHAKE_MIN_POS_READ, //09
    CMD_MOTOR_SETTING_MODE_SHAKE_MAX_POS_SET,   //0a
    CMD_MOTOR_SETTING_MODE_SHAKE_MAX_POS_READ,  //0b
    CMD_MOTOR_SETTING_MODE_SHAKE_HOME_POS_SET,  //0c
    CMD_MOTOR_SETTING_MODE_SHAKE_HOME_POS_READ, //0d
    CMD_MOTOR_SETTING_MODE_SHAKE_HOME_SET,      //0e
    CMD_MOTOR_SETTING_MODE_SHAKE_JOG_RUN, //deprecated  //0f
    CMD_MOTOR_SETTING_MODE_SHAKE_SPEED_SET,     //10
    CMD_MOTOR_SETTING_MODE_SHAKE_SPEED_READ,    //11
    CMD_MOTOR_SETTING_MODE_SHAKE_ASP_POS_SET,   //12
    CMD_MOTOR_SETTING_MODE_SHAKE_ASP_POS_READ,  //13
    CMD_MOTOR_SETTING_MODE_SHAKE_DSP_POS_SET,   //14
    CMD_MOTOR_SETTING_MODE_SHAKE_DSP_POS_READ,  //15
    CMD_MOTOR_SETTING_MODE_SHAKE_CAMERA_POS_SET,
    CMD_MOTOR_SETTING_MODE_SHAKE_CAMERA_POS_READ,
    CMD_MOTOR_SETTING_MODE_SHAKE_DRY_POS_SET,
    CMD_MOTOR_SETTING_MODE_SHAKE_DRY_POS_READ,
    CMD_MOTOR_SETTING_MODE_SHAKE_SAMPLE_DSP_POS_SET,    //1A
    CMD_MOTOR_SETTING_MODE_SHAKE_SAMPLE_DSP_POS_READ,   //1B
    CMD_MOTOR_SETTING_MODE_SHAKE_SPEED_PERIOD_SET,  //1C
    CMD_MOTOR_SETTING_MODE_SHAKE_SPEED_PERIOD_READ, //1D
    CMD_MOTOR_SETTING_MODE_SHAKE_X_AXIS_SPEED_SET = 0x1F,
    CMD_MOTOR_SETTING_MODE_SHAKE_X_AXIS_SPEED_READ,//20
    CMD_MOTOR_SETTING_MODE_X_ACCEL_SPEED_SET,//21
    CMD_MOTOR_SETTING_MODE_X_ACCEL_SPEED_READ,//22
    CMD_MOTOR_SETTING_MODE_X_HOMING,//23
    CMD_MOTOR_SETTING_MODE_X_AXIS_MOVE,//24
    CMD_MOTOR_SETTING_MODE_TRAY_DISP_X_START_SET = 0x28,
    CMD_MOTOR_SETTING_MODE_TRAY_DISP_X_START_READ,
    CMD_MOTOR_SETTING_MODE_TRAY_ASP_X_START_SET = 0x2C,
    CMD_MOTOR_SETTING_MODE_TRAY_ASP_X_START_READ,
    CMD_MOTOR_SETTING_MODE_CAM_HOME_POSITION_SET = 0x32,
    CMD_MOTOR_SETTING_MODE_CAM_HOME_POSITION_READ,
    CMD_MOTOR_SETTING_MODE_BATH_X_POS_SET,
    CMD_MOTOR_SETTING_MODE_BATH_X_POS_READ,
    CMD_MOTOR_SETTING_MODE_CAMERA_END_XPOS_SET,
    CMD_MOTOR_SETTING_MODE_CAMERA_END_XPOS_READ,//37
    CMD_MOTOR_SETTING_MODE_TRAY_CAM_X_START_SET = 0x3A,
    CMD_MOTOR_SETTING_MODE_TRAY_CAM_X_START_READ,
    CMD_MOTOR_SETTING_MODE_STRIP_WIDTH_SET,
    CMD_MOTOR_SETTING_MODE_STRIP_WIDTH_READ
};

#endif // PROTOCOLMOTORSETTINGMODE_H
