#ifndef PROTOCOLCAMERAPARAMETERMODE_H
#define PROTOCOLCAMERAPARAMETERMODE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_PROTOCOL_CAMERA_PARAMETER_MODE
{
    CMD_PROTOCOL_CAMERA_PARAMETER_MODE_BEGIN = 0x00,
    CMD_PROTOCOL_CAMERA_PARAMETER_MODE_END = 0xC9
};


#endif // PROTOCOLCAMERAPARAMETERMODE_H
