#ifndef PROTOCOLDISPENSESAMPLE_H
#define PROTOCOLDISPENSESAMPLE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_DISPENSE_SAMPLE_SETTING
{
    CMD_DISPENSE_SAMPLE_SETTING_PAGE = 0x00, // deprecated
    CMD_DISPENSE_SAMPLE_SETTING_SYRINGE_PUMP_SET ,
    CMD_DISPENSE_SAMPLE_SETTING_SYRINGE_PUMP_READ ,
    CMD_DISPENSE_SAMPLE_SETTING_S_DISPENSE_TEST_START, //deprecated
    CMD_DISPENSE_SAMPLE_SETTING_S_DISPENSE_TEST_PAUSE, //deprecated
    CMD_DISPENSE_SAMPLE_SETTING_AIR_GAP_SET,//2019-01-31 add
    CMD_DISPENSE_SAMPLE_SETTING_AIR_GAP_READ//2019-01-31 add
};


#endif // PROTOCOLDISPENSESAMPLE_H
