#ifndef PROTOCOLWASHINGSOLUTION_H
#define PROTOCOLWASHINGSOLUTION_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_WASHING_SOLUTION_SETTING
{
    CMD_WASHING_SOLUTION_SETTING_PAGE =0x00,
    CMD_WASHING_SOLUTION_SETTING_PUMP_CH7_DISPENSE_SET,
    CMD_WASHING_SOLUTION_SETTING_PUMP_CH7_DISPENSE_READ,
    CMD_WASHING_SOLUTION_SETTING_PUMP_CH8_DISPENSE_SET,
    CMD_WASHING_SOLUTION_SETTING_PUMP_CH8_DISPENSE_READ,
    CMD_WASHING_SOLUTION_SETTING_WS_DISPENSE_CH7_TEST_START,
    CMD_WASHING_SOLUTION_SETTING_WS_DISPENSE_CH7_TEST_PAUSE,
    CMD_WASHING_SOLUTION_SETTING_WS_DISPENSE_CH8_TEST_START,
    CMD_WASHING_SOLUTION_SETTING_WS_DISPENSE_CH8_TEST_PAUSE
};


#endif // PROTOCOLWASHINGSOLUTION_H
