#ifndef PROTOCOLBARCODESETTINGMODE_H
#define PROTOCOLBARCODESETTINGMODE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_BARCODE_SETTING_MODE
{
    CMD_BARCODE_SETTING_MODE_PAGE = 0x00,
    CMD_BARCODE_SETTING_MODE_READ,
    CMD_BARCODE_SETTING_MODE_FIRST_STRIP_POS_SET,
    CMD_BARCODE_SETTING_MODE_FIRST_STRIP_POS_READ,
    CMD_BARCODE_SETTING_MODE_LAST_STRIP_POS_SET,
    CMD_BARCODE_SETTING_MODE_LAST_STRIP_POS_READ,
    CMD_BARCODE_SETTING_MODE_DATA_START,
    CMD_BARCODE_SETTING_MODE_DATA_END,
    CMD_BARCODE_SETTING_MODE_DATA_COMPLETED,
};

enum CMD_QR_SETTING_MODE
{
    CMD_SETTING_MODE_QR_TRAY_POS_MOVE = 0x2E,
    CMD_SETTING_MODE_QR_TRAY_POS_SET = 0x38,
    CMD_SETTING_MODE_QR_TRAY_POS_READ = 0x39
};

#endif // PROTOCOLBARCODESETTINGMODE_H
