#ifndef PROTOCOL_DISPASP_SETTING_MODE_H
#define PROTOCOL_DISPASP_SETTING_MODE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_DISP_ASP_SETTING_MODE
{
    CMD_DISP_ASP_SETTING_MODE_PAGE = 0x00,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_BATH_X_SET,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_BATH_X_READ,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_BATH_Z_SET,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_BATH_Z_READ,
    CMD_DISP_ASP_SETTING_MODE_DISP_BATH_Y_SET,
    CMD_DISP_ASP_SETTING_MODE_DISP_BATH_Y_READ,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_TRAY_X_SET,
    CMD_DISP_ASP_SETTING_MODE_DISP_PIN_TRAY_X_READ,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_TRAY_Z_SET,
    CMD_DISP_ASP_SETTING_MODE_ASP_PIN_TRAY_Z_READ,
    CMD_DISP_ASP_SETTING_MODE_DISP_TRAY_Y_SET,
    CMD_DISP_ASP_SETTING_MODE_DISP_TRAY_Y_READ,
    CMD_DISP_ASP_SETTING_MODE_ASP_HOME_SET,
    CMD_DISP_ASP_SETTING_MODE_ASP_HOME_READ
};

#endif // PROTOCOLDISPASPSETTINGMODE_H
