#ifndef PROTOCOL_TRAY_SETTING_MODE_H
#define PROTOCOL_TRAY_SETTING_MODE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_TRAY_SETTING_MODE
{
    CMD_TRAY_SETTING_MODE_PAGE =0x00,
    CMD_TRAY_SETTING_MODE_HOMMING_SET,
    CMD_TRAY_SETTING_MODE_HOMMING_READ,
    CMD_TRAY_SETTING_MODE_DISP_ASP_POS_SET,
    CMD_TRAY_SETTING_MODE_DISP_ASP_POS_READ,
    CMD_TRAY_SETTING_MODE_ANALYSIS_POS_SET,
    CMD_TRAY_SETTING_MODE_ANALYSIS_POS_READ,
    CMD_TRAY_SETTING_MODE_DRY_POS_SET,
    CMD_TRAY_SETTING_MODE_DRY_POS_READ,
    CMD_TRAY_SETTING_MODE_SPEED_POS_SET,
    CMD_TRAY_SETTING_MODE_SPEED_POS_READ,
    CMD_TRAY_SETTING_MODE_RUN_TIME,
    CMD_TRAY_SETTING_MODE_HOME,
    CMD_TRAY_SETTING_MODE_ANGLE_UP_SET,
    CMD_TRAY_SETTING_MODE_ANGLE_UP_READ,
    CMD_TRAY_SETTING_MODE_ANGLE_DOWN_SET,
    CMD_TRAY_SETTING_MODE_ANGLE_DOWN_READ
};

#endif // PROTOCOL_TRAY_SETTING_MODE_H
