#ifndef PROTOCOLCAMERALEDSETTING_H
#define PROTOCOLCAMERALEDSETTING_H

#include "Network/Protocols/SerialProtocol.h"


enum CMD_CAMERA_LED_SETTING
{

#if USE_FULL_AUTO
    CMD_CAMERA_LED_SETTING_NONE = 0x00,
    CMD_CAMERA_LED_SETTING_LED_PARAM_WRITE_REQ,
    CMD_CAMERA_LED_SETTING_LED_PARAM_WRITE_RESP,
    CMD_CAMERA_LED_SETTING_LED_PARAM_READ_REQ,
    CMD_CAMERA_LED_SETTING_LED_PARAM_READ_RESP,
    CMD_CAMERA_LED_SETTING_LED_PARAM_ONOFF_REQ,
    CMD_CAMERA_LED_SETTING_LED_PARAM_ONOFF_RESP,
    CMD_CAMERA_LED_SETTING_ANLY_X_POS_SET_REQ,
    CMD_CAMERA_LED_SETTING_ANLY_X_POS_SET_RESP,
    CMD_CAMERA_LED_SETTING_ANLY_X_POS_READ_REQ,
    CMD_CAMERA_LED_SETTING_ANLY_X_POS_READ_RESP,
    CMD_CAMERA_LED_SETTING_ANLY_X_END_POS_SET_REQ,
    CMD_CAMERA_LED_SETTING_ANLY_X_END_POS_SET_RESP,
    CMD_CAMERA_LED_SETTING_ANLY_X_END_POS_READ_REQ,
    CMD_CAMERA_LED_SETTING_ANLY_X_END_POS_READ_RESP,
    CMD_CAMERA_LED_SETTING_CAMERA_POS_MOVE_REQ,
    CMD_CAMERA_LED_SETTING_CAMERA_POS_MOVE_RESP,
    CMD_CAMERA_LED_SETTING_CAMERA_POS_MOVE_FINISHIED_REQ,
    CMD_CAMERA_LED_SETTING_CAMERA_POS_MOVE_FINISHIED_RESP
#endif

};


#endif // PROTOCOLCAMERALEDSETTING_H
