#ifndef PROTOCOLETC_H
#define PROTOCOLETC_H
#include "Network/Protocols/SerialProtocol.h"

enum CMD_ETC_SETTING
{
    CMD_ETC_SETTING_PAGE = 0x00,
    CMD_ETC_SETTING_DRY_TEST_SET,
    CMD_ETC_SETTING_DRY_TEST_READ,
    CMD_ETC_SETTING_ASPIRATION_TEST_SET,
    CMD_ETC_SETTING_ASPIRATION_TEST_READ,
    CMD_ETC_SETTING_FAN_TEST_ON,
    CMD_ETC_SETTING_FAN_TEST_OFF,
    CMD_ETC_SETTING_STATUS_LED_ON,
    CMD_ETC_SETTING_STATUS_LED_OFF,
    CMD_ETC_SETTING_DOOR_TEST_ON,
    CMD_ETC_SETTING_DOOR_TEST_OFF,
    CMD_ETC_SETTING_X_AXIS_JOG_MOVE_SET,
    CMD_ETC_SETTING_X_AXIS_JOG_MOVE_READ,
    CMD_ETC_SETTING_Y_AXIS_JOG_MOVE_SET,
    CMD_ETC_SETTING_Y_AXIS_JOG_MOVE_READ,
    CMD_ETC_SETTING_Z_AXIS_JOG_MOVE_SET,
    CMD_ETC_SETTING_Z_AXIS_JOG_MOVE_READ,
    CMD_ETC_SETTING_ASP_JOG_MOVE_SET
};

#endif // PROTOCOLETC_H
