#ifndef PROTOCOLCONTROLREAD_H
#define PROTOCOLCONTROLREAD_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_CONTROL_READ
{
    CMD_CONTROL_READ_SEQUENCE_SELECT = 0x20,
    CMD_CONTROL_READ_START_STEP_NUM,
    CMD_CONTROL_READ_SAMPLE_TOTAL_NUM = 0x2C,

    CMD_END_OF_LIST = 0xFF

};


#endif // PROTOCOLCONTROLREAD_H
