#ifndef PROTOCOL_GENERAL_SETTING_MODE_H
#define PROTOCOL_GENERAL_SETTING_MODE_H

#include "Network/Protocols/SerialProtocol.h"

#if PROTOCOL_VER_0_1 <= PROTOCOL_VER_CURRENT

enum CMD_GENERAL_SETTING_MODE
{
    CMD_GENERAL_SETTING_MODE_POSITION_PAGE,
    CMD_GENERAL_SETTING_MODE_LLD_PAGE,
    CMD_GENERAL_SETTING_MODE_DISPENSE_PAGE,
    CMD_GENERAL_SETTING_MODE_CAMERA_PAGE,
    CMD_GENERAL_SETTING_MODE_ETC_PAGE
};

#endif

#endif // PROTOCOLGENERALSETTINGMODE_H
