#ifndef PROTOCOLCONTROLWRITE_H
#define PROTOCOLCONTROLWRITE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_CONTROL_WRITE
{
    CMD_CONTROL_WRITE_SEQUENCE_SELECT_REQ = 0x10,       // 0010
    CMD_CONTROL_WRITE_SEQUENCE_SELECT_RESP = CMD_CONTROL_WRITE_SEQUENCE_SELECT_REQ,
    CMD_CONTROL_WRITE_CONTINUOUS_RUN_REQ,           // 0011
    CMD_CONTROL_WRITE_CONTINUOUS_RUN_RESP = CMD_CONTROL_WRITE_CONTINUOUS_RUN_REQ,
    CMD_CONTROL_WRITE_STEP_SINGLE_RUN_REQ,
    CMD_CONTROL_WRITE_STEP_SINGLE_RUN_RESP = CMD_CONTROL_WRITE_STEP_SINGLE_RUN_REQ,
    CMD_CONTROL_WRITE_STEP_PROCESS_SINGLE_RUN_REQ,
    CMD_CONTROL_WRITE_STEP_PROCESS_SINGLE_RUN_RESP = CMD_CONTROL_WRITE_STEP_PROCESS_SINGLE_RUN_REQ,
    CMD_CONTROL_WRITE_SEQUENCE_STOP_REQ,
    CMD_CONTROL_WRITE_SEQUENCE_STOP_RESP = CMD_CONTROL_WRITE_SEQUENCE_STOP_REQ,
    CMD_CONTROL_WRITE_PAUSE_REQ,  //0015
    CMD_CONTROL_WRITE_PAUSE_RESP = CMD_CONTROL_WRITE_PAUSE_REQ,
    CMD_CONTROL_WRITE_DEVICE_RESET_REQ, //0016
    CMD_CONTROL_WRITE_DEVICE_RESET_RESP = CMD_CONTROL_WRITE_DEVICE_RESET_REQ,
    CMD_CONTROL_WRITE_DEVICE_CAMERA_MOVE_REQ,
    CMD_CONTROL_WRITE_DEVICE_CAMERA_MOVE_RESP = CMD_CONTROL_WRITE_DEVICE_CAMERA_MOVE_REQ,
    CMD_CONTROL_WRITE_AUTO_CLEAN_REQ,
    CMD_CONTROL_WRITE_AUTO_CLEAN_RESP = CMD_CONTROL_WRITE_AUTO_CLEAN_REQ,
    CMD_CONTROL_WRITE_SAMPLE_TOTAL_NUMBER_REQ = 0x1C,
    CMD_CONTROL_WRITE_SAMPLE_TOTAL_NUMBER_RESP = CMD_CONTROL_WRITE_SAMPLE_TOTAL_NUMBER_REQ,
    CMD_CONTROL_WRITE_SERIAL_NUMBER_REQ, //deprecated 0x1d
    CMD_CONTROL_WRITE_SERIAL_NUMBER_RESP = CMD_CONTROL_WRITE_SERIAL_NUMBER_REQ,//deprecated
    CMD_CONTROL_WRITE_BUZZER_ON_OFF_REQ, //0x1e
    CMD_CONTROL_WRITE_BUZZER_ON_OFF_RESP = CMD_CONTROL_WRITE_BUZZER_ON_OFF_REQ,
    CMD_CONTROL_WRITE_ASPIRATION_SEL_REQ, //0x1f
    CMD_CONTROL_WRITE_ASPIRATION_SEL_RESP = CMD_CONTROL_WRITE_ASPIRATION_SEL_REQ
};


#endif // PROTOCOLCONTROLWRITE_H
