#ifndef PROTOCOL_GENERAL_SETTING_MODE_H
#define PROTOCOL_GENERAL_SETTING_MODE_H

#include "Network/Protocols/SerialProtocol.h"

enum CMD_GENERAL_SETTING_MODE
{
    CMD_GENERAL_SETTING_MODE_LED_LIGHT_POWER_SET = 0x05,
    CMD_GENERAL_SETTING_MODE_LED_LIGHT_POWER_READ,
    CMD_GENERAL_SETTING_MODE_LED_POWER_ON_OFF,
    CMD_GENERAL_SETTING_MODE_WASTE_SENSOR = 0x09
};


#endif // PROTOCOLGENERALSETTINGMODE_H
